language: java
jdk:
  - openjdk17

services:
  - mysql

env:
  global:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=catalog_db
    - MYSQL_USER=root
    - MYSQL_PASSWORD=admin

before_install:
  - mysql -e 'CREATE DATABASE catalog_db;'
  - mysql -u root -e "GRANT ALL PRIVILEGES ON catalog_db.* TO 'root'@'localhost' IDENTIFIED BY 'admin';"
  - sleep 15
  - until mysqladmin ping -h "localhost" --silent; do echo "Waiting for database connection..."; sleep 5; done

install:
  - cd catalog-prod
  - mvn clean install -DskipTests=true

script:
  - mvn test