version: '3.8'
services:
  frontend:
    build:
      context: ./catalog-client
    ports:
      - "80:80"
    networks:
      - catalog-network

  backend:
    build:
      context: ./catalog-prod
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/catalog_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - catalog-network
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: catalog_db
    ports:
      - "3306:3306"
    networks:
      - catalog-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  catalog-network:
    driver: bridge