version: '3.8'
services:
  frontend:
    build:
      context: ./catalog-client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./catalog-client:/app
      - /app/node_modules
    networks:
      - catalog-network

  backend:
    build:
      context: ./catalog-prod
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - catalog-network
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: catalog_db
    ports:
      - "3307:3306"
    networks:
      - catalog-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  catalog-network:
    driver: bridge